In [1]:
import os
from PIL import Image
import numpy as np
import cv2 as cv
import pickle

face_cascade = cv.CascadeClassifier("cascades/data/haarcascade_frontalface_alt2.xml")
recognoizer = cv.face.LBPHFaceRecognizer_create()
#gives the file path
#BASE_DIR = os.path.dirname(os.path.abspath(__file__))

current_id = 0
label_ids = {}
y_labels = []
x_train =[]

BASE_DIR = (r"C:\Users\Anik Chatterjee\Untitled Folder")
image_dir = os.path.join(BASE_DIR,"images")

for root, dirs, files in os.walk(image_dir):
    for file in files:
       if file.endswith("png") or file.endswith("jpg"):
        path = os.path.join(root,file)
        label = os.path.basename(os.path.dirname(path)).replace(" ", "_").lower()
        #print(label,path)
        
        if not label in label_ids:
          label_ids[label] = current_id
        current_id +=1 
        id_ = label_ids[label]
        #print(label_ids)
        #y_label.append(label)
        #x_train.append(path)
        pil_image = Image.open(path).convert("L")
        image_array = np.array(pil_image,"uint8")
        print(image_array)
        faces = face_cascade.detectMultiScale(image_array,scaleFactor=1.5, minNeighbors=5)
        
        for (x,y,w,h) in faces:
           roi = image_array[y:y+w,x:x+h]
           x_train.append(roi) 
           y_labels.append(id_)
#print(y_label)
#print(x_train)

with open("labels.pickle",'wb') as f:
    pickle.dump(label_ids,f)
recognoizer.train(x_train,np.array(y_labels))
recognoizer.save("trainner.yml")


[[223 223 223 ... 230 230 230]
 [223 223 223 ... 230 230 230]
 [223 223 223 ... 230 230 230]
 ...
 [155 155 155 ... 151 147 146]
 [155 155 155 ... 158 156 155]
 [154 155 155 ... 161 160 159]]
[[120 120 121 ... 247 248 249]
 [119 120 120 ... 248 248 249]
 [119 119 120 ... 248 249 249]
 ...
 [ 22  22  23 ... 254 254 254]
 [ 23  23  23 ... 254 254 254]
 [ 24  24  25 ... 254 254 254]]
[[ 92  92  92 ... 172 174 177]
 [ 93  93  92 ... 173 175 178]
 [ 93  93  93 ... 175 178 181]
 ...
 [ 30  29  30 ... 253 253 253]
 [ 29  28  29 ... 253 253 253]
 [ 28  28  28 ... 253 253 253]]
[[ 37  37  37 ...  53  47  46]
 [ 36  36  37 ...  58  53  53]
 [ 36  38  41 ...  59  56  57]
 ...
 [132 136 129 ... 143 143 143]
 [134 127 108 ... 143 143 143]
 [135 118  90 ... 143 143 143]]
[[ 45  44  45 ...  55  63  63]
 [ 45  44  44 ...  56  63  63]
 [ 45  44  43 ...  57  63  63]
 ...
 [ 38  39  39 ... 160 160 160]
 [ 38  38  39 ... 160 160 160]
 [ 37  38  38 ... 160 160 160]]
[[ 41  40  41 ...  53  52  53]
 [ 44  43